// Generated by https://quicktype.io

export interface IDashboardResponse {
  numberOrders: number;
  paidOrders: number;
  notPaidOrders: number;
  numberClients: number;
  numberProducts: number;
  productsNotInStock: number;
  productsLowInStock: number;
}
